M48
; DRILL file {KiCad 7.0.7} date Sun Apr  7 18:23:56 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-07T18:23:56+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0236
%
G90
G05
T1
X5.6299Y-3.6599
T2
X5.0394Y-3.6683
X5.0394Y-3.812
X5.0394Y-4.1407
X5.0394Y-4.2844
T0
M30
